### PR TITLE
added php-cs-fixer action

### PR DESCRIPTION
**Pull request by asccc**

### CODE REVIEW

**Comment by asccc** [comment]
@jr-cologne this does not work properly, because the action checks out the wrong repo on pull-request and is not able to add commits to the forked branch.

see `https://github.com/stefanzweifel/git-auto-commit-action/issues/25`

and since master here is protected, the action is not able to act on push either ... at least i'm not able to test it properly.

**Comment by jr-cologne** [comment]
Hmm, ok. What can we do ... ?

I think I am going to create a new repo to test whether we can enable the action for a protected master branch.
Otherwise, we are just going to accept that it does not work for forks.
Since all people from the forum, who are willing to contribute, are invited to the organization, they can just work on a separate branch of this repo rather than creating a fork.
A third option would be to add php-cs as a status check, not as an automatically executed fixer.

Edit:
Ok, unfortunately, it is not possible to push to protected branches from GitHub actions.

So, would you prefer to use php-cs-fixer on PRs without supporting forks or should we switch to php-cs on PRs?

**Comment by asccc** [comment]
Well, i 'm not sure what we can do here. Other projects simply nitpick on pull-requests if the syntax is off ... 😆

**Comment by wookiefriseur** [comment]
> Well, i 'm not sure what we can do here. Other projects simply nitpick on pull-requests if the syntax is off ... 😆

I wouldn't mind PRs being rejected / blocked by a bot until the syntax is fixed and tests work. I like the pain.

We could add a "How to contribute", to show how to setup the auto formatter in VSCode, PHPStorm and so on, so that nobody has to run it manually.

**Comment by asccc** [comment]
I think this is doable. php-cs-fixer has a dry-run option and exits with something other than 0 if something can be fixed

**Comment by asccc** [comment]
works now

**Comment by jr-cologne** [comment]
Yay! Thank you for going through this hassle. :tada: :smiley:

**Review by jr-cologne — APPROVED** [review]

**Pull request merged**
